name = "my-turnstile-demo"
compatibility_date = "2025-05-30"
pages_build_output_dir = "./public"

[site]
bucket = "./public"

[vars]
TURNSTILE_SECRET_KEY = "0x0000000000000000000000000000000000000000" # replace to your key

[env.production]
compatibility_flags = ["nodejs_compat"]
